{{- if .Values.ingress.enabled -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "netbird-log-forwarder.fullname" . }}-tls
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "netbird-log-forwarder.labels" . | nindent 4 }}
spec:
  dnsNames:
  {{- range .Values.ingress.hosts }}
  - {{ .host }}
  {{- end }}
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: {{ include "netbird-log-forwarder.fullname" . }}-tls
  usages:
  - digital signature
  - key encipherment
{{- end }}
