apiVersion: v1
kind: Service
metadata:
  name: {{ include "netbird-log-forwarder.fullname" . }}
  labels:
    {{- include "netbird-log-forwarder.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ipFamilyPolicy: {{ .Values.service.ipFamilyPolicy }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: https
  selector:
    {{- include "netbird-log-forwarder.selectorLabels" . | nindent 4 }}
